### ISSUE TITLE
Pre-Order?

### ISSUE THREAD

**Issue by mnagatos101** [markjprice/tools-skills-net8#1]
I'm still making my way with the first 2 .net 8 books, but will this title be available for pre-order soon?

**Comment by markjprice** [comment]
Pre-orders usually start on Amazon about one month before publish date. Currently the book is planned to publish in summer 2024.

**Comment by mnagatos101** [comment]
Sounds great!  Gives me a chance to finish your other 2 books.  Huge fan!
