### ISSUE TITLE
Need upper S in builder.Services.AddKeyedsingleton

### ISSUE THREAD

**Issue by P9avel** [markjprice/tools-skills-net8#10]
Hi,
![image](https://github.com/user-attachments/assets/9eac40d9-8b4e-44d2-8e6a-09b48cfd35d6)

**Comment by markjprice** [comment]
Thanks! I've added an item for this here:
https://github.com/markjprice/tools-skills-net8/blob/main/docs/errata/errata.md#page-356---registering-multiple-implementations
