### ISSUE TITLE
Need 'warnings as errors'

### ISSUE THREAD

**Issue by P9avel** [markjprice/tools-skills-net8#11]
Hi
![image](https://github.com/user-attachments/assets/4b5dccf0-77fc-4ec7-85de-777d8e640673)

**Comment by P9avel** [comment]
and here
![image](https://github.com/user-attachments/assets/d63b6f25-a892-40bf-995c-438d93dd9c4f)

**Comment by markjprice** [comment]
Thanks. I've added an errata item for these here:
https://github.com/markjprice/tools-skills-net8/blob/main/docs/errata/errata.md#page-388---creating-a-sut-page-401---controlling-test-fixtures
