### ISSUE TITLE
Strange 'f.' in 'f.Finance.Currency( ).Code'

### ISSUE THREAD

**Issue by P9avel** [markjprice/tools-skills-net8#14]
Hi
![image](https://github.com/user-attachments/assets/a4890953-6334-46d8-ab4e-3cb040ea6788)

**Comment by markjprice** [comment]
Thanks. I've added an errata item for this here:
https://github.com/markjprice/tools-skills-net8/blob/main/docs/errata/errata.md#page-415---generating-fake-data-with-bogus
