### ISSUE TITLE
Need Integration instead Unit

### ISSUE THREAD

**Issue by P9avel** [markjprice/tools-skills-net8#15]
Hi,

![image](https://github.com/user-attachments/assets/f08fcdbb-bc11-48d3-928e-a36b634bebf5)

**Comment by markjprice** [comment]
Thanks! I've added an item for this here:
https://github.com/markjprice/tools-skills-net8/blob/main/docs/errata/errata.md#page-427---walkthrough-of-an-example-integration-test
