### ISSUE TITLE
Incorrect 'docker run' 4 times

### ISSUE THREAD

**Issue by P9avel** [markjprice/tools-skills-net8#17]
Hi,

![image](https://github.com/user-attachments/assets/4876ff3b-9597-4ded-8fe6-51059815001a)

**Comment by markjprice** [comment]
Thanks! I've added an improvement item here:
https://github.com/markjprice/tools-skills-net8/blob/main/docs/errata/improvements.md#page-524---docker-command-line-interface-cli-commands-page-527---configuring-ports-and-running-a-container
