### ISSUE TITLE
Many issues in docker layers

### ISSUE THREAD

**Issue by P9avel** [markjprice/tools-skills-net8#18]
Hi, i am think you used old template for layers description. 

![image](https://github.com/user-attachments/assets/e168f1d1-b06e-49fa-bf4c-3411d61be0b6)

**Comment by markjprice** [comment]
*Figure 15.7* on page 536 was intended as an example of Docker commands and how they are layered. It was not designed to match the file used in the Step 4 instruction on page 542. But you are correct the figure has multiple issues anyway so must be fixed. I like your idea that the figure match the file the reader's creat so I have done that too. I have added an errata item for this here:
https://github.com/markjprice/tools-skills-net8/blob/main/docs/errata/errata.md#page-536---docker-image-hierarchy-and-layers
