### ISSUE TITLE
Issue with Customers.CustomerId regular expression

### ISSUE THREAD

**Issue by OpticOrange** [markjprice/tools-skills-net8#19]
Chapter 1 page 29

Should the regular expression be ^[A-Z]{1,5}$

The text says maximum of five characters implying something like ABC would also be valid, but the regular expression provided only allows exactly five.  

![image](https://github.com/user-attachments/assets/2163c1d9-23bf-4e45-8bea-b2b9fbcbfe8e)

**Comment by P9avel** [comment]
DbContext was generated  from DB  structure. I think the phrase 'to a maximum' should be removed from the text

**Comment by markjprice** [comment]
Thanks! I've added an improvement item for this here:
https://github.com/markjprice/tools-skills-net8/blob/main/docs/errata/improvements.md#page-29---creating-a-class-library-for-entity-models-using-sql-server
