### ISSUE TITLE
Missing 's' i pros

### ISSUE THREAD

**Issue by P9avel** [markjprice/tools-skills-net8#20]
Hi, 
![image](https://github.com/user-attachments/assets/eaa8a86d-04ae-4c9e-8f18-7d2da36b89c2)

**Comment by markjprice** [comment]
Thanks! I've added an errata item for this here:
https://github.com/markjprice/tools-skills-net8/blob/main/docs/errata/errata.md#page-579---docker-versus-podman-for-containers
