### ISSUE TITLE
Need upper case

### ISSUE THREAD

**Issue by P9avel** [markjprice/tools-skills-net8#21]
Hi,

![image](https://github.com/user-attachments/assets/87692c8b-8c28-4949-812c-5c08f9b6eea2)

**Comment by markjprice** [comment]
Thanks! I've added an errata item for this here:
https://github.com/markjprice/tools-skills-net8/blob/main/docs/errata/errata.md#page-622---builder-pattern-example

**Comment by P9avel** [comment]
Hi, i think incorrect fix :( You wrote "But we are building a "user profile", not a "product". In the next edition I will fix this."

I think  need 'Product' but from upper case. Look 

![image](https://github.com/user-attachments/assets/c5e676de-1627-4f47-b2fe-f830b59b5334)

**Comment by markjprice** [comment]
Ah, I see what you mean now. Yes, you're right. I'd forgotten **Product** refers to the official term for the object being built. I've updated the errata item. Thanks!
