### ISSUE TITLE
Mistakes in Understanding stack and heap memory

### ISSUE THREAD

**Issue by P9avel** [markjprice/tools-skills-net8#5]
Hi, i am found error.
![image](https://github.com/user-attachments/assets/144ecde6-9bc8-49d1-98ae-90472b5f5c63)

Correct here for .net8
![image](https://github.com/user-attachments/assets/150cbc4b-b701-402c-9a19-39dbc9c941db)

**Comment by markjprice** [comment]
What, specifically, are you claiming is "incorrect"? 

Both my statements and the table show that on Linux and maxOS the default stack size is 8Mb, and on Windows I say it it is 1 MB and the table says it is 1.5Mb, but note the asterisk by the 1.5Mb in the table which indicates that there is more to the story. But you don't show what that asterisk note says. And you have included a screenshot of the table without a link to its origin.

**Comment by markjprice** [comment]
I've done some digging and I think I've found the web page where you got the table. It does not explain the asterisk. But the comments below are instructive so I've created an improvement item for this here:
https://github.com/markjprice/tools-skills-net8/blob/main/docs/errata/improvements.md#page-156---understanding-stack-and-heap-memory

**Comment by P9avel** [comment]
Many thx for your work
