### ISSUE TITLE
2 times call aes.CreateDecryptor()

### ISSUE THREAD

**Issue by P9avel** [markjprice/tools-skills-net8#6]
Hi, i am found duplicate

![image](https://github.com/user-attachments/assets/a9b56faf-4d4b-4372-aed5-654080e7cdfb)

**Comment by markjprice** [comment]
Thanks! I've added an errata item for this here:
https://github.com/markjprice/tools-skills-net8/blob/main/docs/errata/errata.md#page-285---encrypting-symmetrically-with-aes
